### PR TITLE
Error messages should show in client side logs

### LINKED ISSUE #651: Error messages should show in client side logs
**Context**
We've gotten feedback that currently, error messages do not show up in the logs. We would like to include them for easier debugging.

**A/C's**
- [ ] When a 500 error occurs, I can see the error code and message in the client side logs
- [ ] When a 400 error occurs, I can see the error code and message in the client side logs
- [ ] When an error occurs, I can see the error code and message in the client side logs

### PR DESCRIPTION
**Pull request by akhil-ghatiki**
## Description of Change

Error messages will be shown in client side logs. This eases up debugging a little. 
This PR partially fixes #651

If the changes look good, i will raise another PR covering all the cases after getting feedback

## Checklist

- [x] PR description included and stakeholders cc'd
- [x] yarn test passes
- [x] yarn lint has been run
- [x] git pre-commit hook is successfully executed.

@4upz-tw 

© 2021 Thoughtworks, Inc.

### CODE REVIEW

**Comment by 4upz** [comment]
Hi @akhil-ghatiki , thanks for opening this PR for feedback! I see that you are using our Logger for printing the error messages. I think this is unneeded, and that a simple console.log can be used since logs go to the browser. 

For additional context, our Logger in the Common package was meant to provide extensive logging in the API. The scope of this issue (#651 ) is to only show the error message and details in the browser logs, which can be done using the standard console logging. Bonus points if this same message can be shown in the UI's error page. Hopefully, that clears things up! Sorry if I confused you with my initial explanation.

Also, try to refrain from including our trunk's commits in your PR. It can bloat your PR changes, making it harder to review the changes you actually made. Unless, these changes contain merge conflicts then we can address them after review.

Feel free to let me know if you have any questions!

**Comment by akhil-ghatiki** [comment]
@4upz I will make the changes accordingly, thanks for the feedback. 

`Also, try to refrain from including our trunk's commits in your PR. It can bloat your PR changes, making it harder to review the changes you actually made. Unless, these changes contain merge conflicts then we can address them after review.`

I did not get this. I can see the my commit has only 2 files. https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/931/commits/4f505dc63032e45823aa1e24294c031b1f5467e9

**Comment by 4upz** [comment]
@akhil-ghatiki Sorry, for the confusion. Yes, that individual commit shows your changes. But the commits attached to this PR also contain commits that are already in trunk (most likely from you merging into your fork). As a result, it attaches additional commits to this PR which makes it hard to view the overall File Changes (feature usually used for review) of this PR without seeing file changes from those commits as pictured below. So I was recommending to refrain from merging trunk until the PR is complete to minimize this. It's a small thing, as I can still review each individual commit, it just makes review faster not to do so (especially as more commits are added). Hopefully, that makes sense! If not, no need to worry about it 😃  

image

**Comment by akhil-ghatiki** [comment]
Thanks @4upz I will raise a different PR with the changes.

**Pull request closed without merging**
