### PR TITLE
Add support for additional Azure regions

### LINKED ISSUE #592: Add support for additional Azure regions
## Context
seeking contributor
#### Overview
Adding support for Azure regions is not extremely straightforward. In different places, the naming of these regions is not exactly the same or predictable, so initially our team has only been able to add support for regions we are currently using. We would appreciate the addition of any regions not yet supported that you are using.

## Acceptance Criteria
- [ ] When I have usage in a previously unsupported Azure region, I now see the data for that region added to the total data for my Azure usage
- [ ] When I have usage in a previously unsupported Azure region, I now see my usage for that region within the bar chart, with the appropriate label, percentage of usage, color for grid intensity
- [ ] When I have usage in a previously unsupported Azure region, I now see that region in the region bar chart with a hover that has the region name and cloud provider, and total co2e for this region
- [ ] When I reference a new Azure region, I should follow the existing naming conventions
- [ ] When I have usage for a previously unsupported region that I can see this region in the region map and it's grid intensity is listed in the methodology on the microsite (Please reach out to the Green Cloud team if these two need to be completed - we will handle it.)

## Tech Tasks
- [ ] Changes to be made in packages/azure/src/lib/AzureRegions.ts
- [ ] Add appropriate test coverage, including edge cases.
- [ ] Run Changesets, bump any packages that have been updated/changed
- [ ] Did you make changes to the client, api or cli package? If so, considering updating the create-app templates.
- [ ] If any create-app templates have been updated, make sure to run the [test-create-app script](https://docs.google.com/document/d/1Ei6Cb2DjwEJUNtpULJSxbOuIdAfCARERgE3BSsKWrsc/edit) to ensure it still works properly.

## Review Tasks
- [ ] eg. specific QA details, update methodology, or update microsite

### PR DESCRIPTION
**Pull request by LvffY**
## Description of Change

We'll had support for more Azure regions (at least France regions).

Relates to #592 

## Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] tests are changed or added
- [ ] yarn test passes
- [ ] yarn lint has been run
- [ ] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [ ] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
- [ ] relevant documentation is changed or added

## Notes

Additional information relevant to the changes

© 2021 Thoughtworks, Inc.

### CODE REVIEW

**Comment by LvffY** [comment]
@ericksod @4upz-tw I tried added the Azure regions listed with `az account list-locations -o table`. Unfortunately, I'm unable to understand how to apply the estimations factor that you mention. 

Could you give me an example ? If you prefer, I can let you fullfil the estimator.

**Comment by 4upz-tw** [comment]
Hi @LvffY! Thanks for jumping on this and filling in some of these regions for us! It's extremely helpful and appreciated since we've only been limited to the regions we use within our organization. 

In regards to the emissions factors, this refers to the rate in metric tons at which energy grids in that region emit CO2e per kWh. A table of what we have so far can be found in the [Azure emissions appendix section](https://www.cloudcarbonfootprint.org/docs/methodology/#azure-2) of our methodology. You can also see the source in which we get these factors from which include the [EPA](https://www.epa.gov/egrid/download-data) and [carbonfootprint.com](https://www.carbonfootprint.com/docs/2020_07_emissions_factors_sources_for_2020_electricity_v1_3.pdf). 

Adding these factors are a matter of researching and grabbing these numbers from one of the listed sources, adding them to [AzureFootprintEstimationConstants.ts](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/trunk/packages/azure/src/domain/AzureFootprintEstimationConstants.ts) file for the `AZURE_EMISSIONS_FACTORS_METRIC_TON_PER_KWH` constant, then updating the table in the methodology.

Let us know if you have any questions and if this is something you'd be interested in exploring. Otherwise, our team is happy to validate them and add them to your PR!

**Comment by LvffY** [comment]
@4upz-tw I think I have a first working version. I'd like to test it more (i.e with integrations tests for example by connecting my own Azure subcription), but I don't know how to do so ? 

More over, could you check if I missed something from your perspective ?

**Comment by LvffY** [comment]
I'll just be off some days, so don't worry if I don't answer :)

**Comment by LvffY** [comment]
@4upz Should be finish from my side. Do not hesitate if I miss something

**Review by 4upz — APPROVED** [review]
Awesome! Looks good, thanks again for your work on this! @LvffY 

Sorry for missing your question regarding testing. A good way to test it would be to edit one of the tests for the `ConsumptionManagement.test.ts` to include one of the new regions and to verify that you get the expected calculated c02e for that emissions factor.

Totally not necessary since the sources are listed and only new constants are being added. However, you're totally welcome to do so.

**Comment by LvffY** [comment]
> Sorry for missing your question regarding testing. A good way to test it would be to edit one of the tests for the `ConsumptionManagement.test.ts` to include one of the new regions and to verify that you get the expected calculated c02e for that emissions factor.

Thanks @4upz :)

I don't think I'll have time to dig into the test part so @ccasher can review this PR without it. If i have time, i'll let you know. If I don't, because I just added some element to an existing enumeration, I think I can live with that :)

Now, TBH, I came here because I found the issue in the [ccf-backstage-plugin](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin). When this PR is merged, will a new version be generated directly or do you have any internal processes ? *I'm asking this to have an idea of the time needed to use this fix into my backstage instance.*

**Comment by 4upz** [comment]
> > Sorry for missing your question regarding testing. A good way to test it would be to edit one of the tests for the `ConsumptionManagement.test.ts` to include one of the new regions and to verify that you get the expected calculated c02e for that emissions factor.
> 
> Thanks @4upz :)
> 
> I don't think I'll have time to dig into the test part so @ccasher can review this PR without it. If i have time, i'll let you know. If I don't, because I just added some element to an existing enumeration, I think I can live with that :)
> 
Totally fine! They're just updated constants, so the test isn't necessary and it can be merged without it.
> Now, TBH, I came here because I found the issue in the [ccf-backstage-plugin](https://github.com/cloud-carbon-footprint/ccf-backstage-plugin). When this PR is merged, will a new version be generated directly or do you have any internal processes ? _I'm asking this to have an idea of the time needed to use this fix into my backstage instance._

Nice, glad to hear that you're using the Backstage plugin! So once this PR is merged, this change will be queued for the next release for CCF and its packages -- and will be included in the Azure package's release. After this gets released, the rest will be straightforward as we'd just need to double check that the plugin is using the new package and that it's peer dependencies are properly updated so that people can use it.

I'd say it should only take about a week, but we can keep you updated!

**Review by ccasher — APPROVED** [review]

**Pull request merged**
