### PR TITLE
[813] upgrade client to react v18

### LINKED ISSUE #813: Upgrade Client to React 18
## Feature Suggestion
**Is your feature request related to a problem? Please describe.**
React 18 has [released](https://reactjs.org/blog/2022/03/29/react-v18.html) and it contains a plethora of enhancements that could be valuable to bring to our client, with the most notable being: concurrent rendering and automatic batching for state updates. These improvements could bring immediate performance enhancements to our client app by reducing unnecessary re-renders and allowing for other performance enhancements through the new hooks that are available.

**Scope**
Updating to React 18 is a surprisingly quick task , as you just have to run the `yarn up` command for `react` and `react-dom`, then change the `index.tsx` file to use the new rendering API. Any additional features are optional and can be implemented on an as-needed basis.

**Additional context**
Updating to React 18 does have a slight styling affect on the dashboard has Material UI has yet to release an update to make it fully compatible. We'll have to wait for them to do a new release to make it compatible with React 18's changes. Their roadmap and milestone tracker can be viewed here: https://github.com/mui/material-ui/milestone/45

## Before Implementation

- [ ] Use React Devtools' Profiler to measure performance improvements of state batching. A good example would be to record the render time after selecting/deselecting one of the filters.
- [ ] Take screenshot comparisons of React 18 vs React 17 improvements and add to this issue
- [ ] Confirm that MUI is compatible and upgrade to new `mui-core` package with the React 18 changes

## Possible Implementation

- [ ] Run `yarn up react react-dom` to update to the latest version of React
- [ ] In the client package, make the following change to the root `index.tsx` file:
``` diff

- import React from 'react'
- import ReactDOM from 'react-dom'
+ import { createRoot } from 'react-dom/client'
import { Root } from './Root'

- ReactDOM.render(<Root />, document.getElementById('root'))

+ const container = document.getElementById('root')
+ const root = createRoot(container)
+ root.render(<Root />)

```

### PR DESCRIPTION
**Pull request by Samridhi-98**
## Description of Change

Write a brief but concise description of the changes you have made while also making sure to **link the relevant issue number to this PR** _( e.g. fixes #ISSUE-NUMBER - optional short description)_

**Changes Done:**

- Updated package.json - `react, react-dom, react-test-renderer, react-router-dom`
- Updated `index.tsx` & `App.tsx`
- Fix broken UI on `emission metric page` & `recommendation page`

**Need to fix:**

- Integration test failing 

**Fixes:** #813 

## Checklist

- [ ] PR description included and stakeholders cc'd
- [x] tests are changed or added
- [x] yarn test passes
- [x] yarn lint has been run
- [ ] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [ ] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
- [ ] relevant documentation is changed or added

## Before Screenshot

Screenshot 2022-12-21 at 4 10 51 PM

Screenshot 2022-12-21 at 4 12 14 PM

Screenshot 2022-12-21 at 4 11 34 PM

Screenshot 2022-12-21 at 4 11 18 PM

Screenshot 2022-12-21 at 4 11 00 PM

## After Screenshot

Screenshot 2022-12-23 at 9 43 59 AM

Screenshot 2022-12-23 at 9 45 37 AM

image

image

image

© 2021 Thoughtworks, Inc.

### CODE REVIEW

**Comment by Samridhi-98** [comment]
Hey @4upz , please review my PR.

**Comment by 4upz** [comment]
Thanks for opening @Samridhi-98! Will give it a review as soon as I can

**Review by 4upz — APPROVED** [review]
This looks great, @Samridhi-98! Thank you for tackling this! I'll go ahead and merge this in.

**Comment by 4upz** [comment]
Integration tests fixes will be followed in https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/1005

**Pull request merged**
