### PR TITLE
Feat/add helm chart

### PR DESCRIPTION
**Pull request by jbdelpech**
## Description of Change

Hello, for people that are wondering how to deploy Cloud Carbon Footprint app in Kubernetes with minimal setup, here is what I crafted for my company.

I did see that [a previous PR was opened a long time ago now](https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/pull/369), but I thought it was missing some important points like api and client split in different workloads.

Feel free to use it as is or to iterate on.

## Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] tests are changed or added
- [ ] yarn test passes
- [ ] yarn lint has been run
- [ ] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [ ] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
- [ ] relevant documentation is changed or added

## Notes

Additional information relevant to the changes

© 2021 Thoughtworks, Inc.

### CODE REVIEW

**Comment by ccasher** [comment]
Hi @jbdelpech, thank you very much for submitting this PR! We will plan to review in the next couple weeks since our team has a short work week with the holiday this week.

**Comment by tw-tmac** [comment]
I tried to install via helm but the client is failing with the following error:

```
2023/01/27 18:37:41 [emerg] 1#1: host not found in resolver "proxy_set_header" in /etc/nginx/nginx.conf:13
nginx: [emerg] host not found in resolver "proxy_set_header" in /etc/nginx/nginx.conf:13
```

I tried deploying on both k3s and EKS 1.22 and getting the same error. Did you encounter this when you tried it on your cluster?

**Comment by jbdelpech** [comment]
> I tried to install via helm but the client is failing with the following error:
> 
> ```
> 2023/01/27 18:37:41 [emerg] 1#1: host not found in resolver "proxy_set_header" in /etc/nginx/nginx.conf:13
> nginx: [emerg] host not found in resolver "proxy_set_header" in /etc/nginx/nginx.conf:13
> ```
> 
> I tried deploying on both k3s and EKS 1.22 and getting the same error. Did you encounter this when you tried it on your cluster?

Hello @tw-tmac, I figured out that a semicolon was missing at the end of resolver line.

I just added it and pushed the fix.

**Comment by tw-tmac** [comment]
oh nice catch! approved!

**Review by tw-tmac — APPROVED** [review]

**Comment by MattiDeGrauwe** [comment]
@jbdelpech have you been able to use any way of cache through Kubernetes? It seems impossible to attach a PVC since the cache location is not configurable. Connecting to MongoDB also doesn't seem to make the caching work properly.

Were you able to make use of the cache functionalities? Thanks in advance! :)

**Pull request merged**
