### PR TITLE
Add support for auth with Azure using an SPN and a certificate

### LINKED ISSUE #1269: Support for SPN and Certificate Authentication
## Feature Suggestion

**Is your feature request related to a problem? Please describe.**
The current version of the library does not support authenticating using a Service Principal Name (SPN) and a certificate. This limitation hinders users who require this authentication method for their Azure services.

**Describe the solution you'd like**
I propose setting `AZURE_AUTH_MODE` to `CERTIFICATE` to indicate SPN and certificate authentication. Additionally, users should be able to specify the path to the certificate file using the `AZURE_CERTIFICATE_PATH` environment variable.

**Describe alternatives you've considered**
One alternative would be to continue using the existing authentication methods, such as client ID and client secret, but these may not meet the security or organizational requirements of some users. Enabling SPN and certificate authentication provides a more flexible and secure option.

**Additional context**
This feature would be particularly useful for users who follow best practices in securing their Azure applications or for scenarios where the use of client secrets is restricted.

## Possible Implementation

1. Introduce a new value,`CERTIFICATE`, for `AZURE_AUTH_MODE` to indicate SPN and certificate authentication.
2. Allow users to specify the path to the certificate file using the `AZURE_CERTIFICATE_PATH` environment variable.
3. In the code, implement logic to check the value of `AZURE_AUTH_MODE`. If set to `CERTIFICATE`, use SPN and certificate authentication.

This implementation provides a straightforward way for users to opt for SPN and certificate authentication when needed.

### PR DESCRIPTION
**Pull request by cahitihac**
## Description of Change

Adds support for authentication with Azure using an SPN and a certificate. This fixes #1269.

## Checklist

- [x] PR description included and stakeholders cc'd
- [x] yarn test passes
- [x] yarn lint has been run
- [x] git pre-commit hook is successfully executed.
- [x] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)

## Notes

Additional information relevant to the changes

© 2021 Thoughtworks, Inc.

### CODE REVIEW

**Comment by cahitihac** [comment]
**~/develop/cahitihac/cloud-carbon-footprint/packages/azure | on trunk > yarn run test**
 PASS  src/__tests__/ConsumptionDetailRow.test.ts
 PASS  src/__tests__/AdvisorRecommendations.test.ts
 PASS  src/__tests__/AzureCredentialsProvider.test.ts
 PASS  src/__tests__/ConsumptionManagement.test.ts
 PASS  src/__tests__/AzureAccount.test.ts

Test Suites: 5 passed, 5 total
Tests:       1 skipped, 27 passed, 28 total
Snapshots:   0 total
Time:        3.042 s
Ran all test suites.

**~/develop/cahitihac/cloud-carbon-footprint/packages/common | on trunk > yarn run test**
 PASS  src/__tests__/RecommendationTarget.test.ts
 PASS  src/__tests__/Errors.test.ts
 PASS  src/helpers/__tests__/unitConversion.test.ts
 PASS  src/helpers/__tests__/helpers.test.ts
 PASS  src/__tests__/Config.test.ts
 PASS  src/__tests__/EstimationResult.test.ts
 PASS  src/__tests__/Logger.test.ts
 PASS  src/__tests__/EmissionsFactors.test.ts
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.

Test Suites: 8 passed, 8 total
Tests:       60 passed, 60 total
Snapshots:   0 total
Time:        2.68 s
Ran all test suites.

**Comment by 4upz** [comment]
@cahitihac Thanks for opening this PR! I think this is a valuable add. The implementation overall looks good -- just one question before merging:

I haven't had much hands-on with using a SPN in Azure, so I'm wondering if there is any additional setup required for enabling/configuring an SPN and certificate within the Azure portal. If so, would it be worth calling out and making a note of it within the [documentation for Authentication Options](https://www.cloudcarbonfootprint.org/docs/azure#options-for-azure-authentication) -- even if just linking to its section within Azure docs?

**Comment by cahitihac** [comment]
> @cahitihac Thanks for opening this PR! I think this is a valuable add. The implementation overall looks good -- just one question before merging:
> 
> I haven't had much hands-on with using a SPN in Azure, so I'm wondering if there is any additional setup required for enabling/configuring an SPN and certificate within the Azure portal. If so, would it be worth calling out and making a note of it within the [documentation for Authentication Options](https://www.cloudcarbonfootprint.org/docs/azure#options-for-azure-authentication) -- even if just linking to its section within Azure docs?

@4upz - added a guidance for enabling SPN-based authentication. Please review, thanks.

**Comment by 4upz** [comment]
@cahitihac Awesome, thanks for the documentation update! Everything LGTM -- I'll merge this in 🚀

**Review by 4upz — APPROVED** [review]

**Pull request merged**
