### PR TITLE
Adding managed-identity support for Azure

### PR DESCRIPTION
**Pull request by FlorianWeissDev**
## Description of Change

Adding case for the AzureCredentialsProvider to use DefaultAzureCredential in case of MANAGED_IDENTITY.

## Checklist

- [x] PR description included and stakeholders cc'd
- [ ] tests are changed or added
- [ ] yarn test passes
- [x] yarn lint has been run
- [ ] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [ ] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
- [ ] relevant documentation is changed or added

## Notes

Same as for PR #1158 this change would only add a test case asserting that a mocked library was called. So we left it out.

Locally I have failing tests but those do not seem to be related to our changes as they are also failing on the trunk branch for me. Would be nice if you could validate the tests as well.

© 2021 Thoughtworks, Inc.

Kind regards,
Florian Weiß
im Auftrag der DB Systel GmbH

### CODE REVIEW

**Review by ccasher — APPROVED** [review]
Looks great! Thank you, @FlorianWeissDev!

**Comment by ccasher** [comment]
Just need to get the linting error fixed:
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/actions/runs/8615922572/job/23834960524?pr=1330#step:9:23

**Review by ccasher — CHANGES_REQUESTED** [review]
Linting issues

**Comment by FlorianWeissDev** [comment]
> Just need to get the linting error fixed: https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/actions/runs/8615922572/job/23834960524?pr=1330#step:9:23

Thank you for the review. Apologies for the delayed response, I'm on it.

**Comment by FlorianWeissDev** [comment]
@ccasher I've had a lot of issues with the unit tests locally. I expect, that the pipeline is going to fail in the next step. Is the  Google Group the right place to get help to solve the test issues?

The failing tests seem to be unrelated to my changes as they are also failing on the trunk branch for me.

**Comment by FlorianWeissDev** [comment]
The out of memory error is not caused by the changes in this PR as I can also reproduce it on the trunk. Is this a known issue?

**Comment by 4upz** [comment]
@FlorianWeissDev sorry for the slow follow-up and roadblocks on this! I see that there's some memory issues with the test that's causing it to fail the checks. I'm currently looking into it to see if I can reproduce.

**Comment by 4upz** [comment]
@FlorianWeissDev This seems to be a dependency or issue caused by a mismatch of node versions -- especially since the CI pipelines for trunk seem to be intact and I only encounter slow/failing tests when using Node 16/18. I've pushed some fixes to our CI that should allow for me to verify this. In the meantime, would you mind doing the following?

- Confirming which version of node you were running when you encountered the heap issue on trunk
- Reverting the client changes that you made in this PR. Since you only added Azure functionality, you shouldn't be encountering client package linting errors. This could've been a mistake due to your branch being slightly behind trunk.

I ran and tested your branch locally and everything seemed fine. I'd be okay with merging in the changes and troubleshooting any test/lint issues ourselves within trunk.

**Comment by FlorianWeissDev** [comment]
Good morning @4upz, thank you for your response and no worries about the delay. About your questions:

- I've been using Node 20.12.2 locally and I'm pretty sure I've not updated since working on this PR. To be sure I've just updated to the latest LTS (20.13.1) and I'm gonna check if I still encounter the issues on the updated trunk branch.
- Sure, I will revert the linting changes that are not Azure related. Probably later today.

I will give you an update later.

**Comment by FlorianWeissDev** [comment]
@4upz okay, the tests are now running fine for me as well. 

- Updated node to 20.13.1 locally, but 20.12.2 also works fine.
- Rebased onto trunk.
- Removed the client package linting changes.

I've not pushed the rebased version of the branch yet, as you are still working on it as well.

**Comment by FlorianWeissDev** [comment]
Linting is green, too.

**Comment by 4upz** [comment]
> @4upz okay, the tests are now running fine for me as well.
> 
> * Updated node to 20.13.1 locally, but 20.12.2 also works fine.
> * Rebased onto trunk.
> * Removed the client package linting changes.
> 
> I've not pushed the rebased version of the branch yet, as you are still working on it as well.

Thanks for confirming @FlorianWeissDev! You're good to push up your changes. The trunk and CI is stable now

**Comment by FlorianWeissDev** [comment]
> Thanks for confirming @FlorianWeissDev! You're good to push up your changes. The trunk and CI is stable now

@4upz  I rebased the branch onto trunk again and pushed the reverted changes. Tests and linting are green.

**Comment by 4upz** [comment]
> > Thanks for confirming @FlorianWeissDev! You're good to push up your changes. The trunk and CI is stable now
> 
> @4upz I rebased the branch onto trunk again and pushed the reverted changes. Tests and linting are green.

Thanks! Everything looks good -- I'll merge it in

**Review by 4upz — APPROVED** [review]

**Comment by FlorianWeissDev** [comment]
@4upz thank you for your assistance today!

**Comment by 4upz** [comment]
@FlorianWeissDev No problem, thanks for your patience and for contributing!

**Pull request merged**
