### PR TITLE
Use @google-cloud/iam-credentials instead of googleapis

### LINKED ISSUE #275: Reduce package size
After installing the `core` package in an empty NPM project using `npm install --save @cloud-carbon-footprint/core` here is the corresponding node_module directory:

```
> ls node_modules/ | xargs -I {} du -h -d0 ./node_modules/{} | grep 'M\s' | sort -k1 -n
1.1M	./node_modules/ajv
1.3M	./node_modules/@opencensus
1.7M	./node_modules/@cloud-carbon-footprint
1.8M	./node_modules/node-forge
2.2M	./node_modules/@grpc
2.6M	./node_modules/@types
2.6M	./node_modules/underscore
2.9M	./node_modules/date-utils
3.0M	./node_modules/ramda
5.1M	./node_modules/moment
6.3M	./node_modules/google-gax
7.3M	./node_modules/protobufjs
 12M	./node_modules/@azure
 13M	./node_modules/@google-cloud
 62M	./node_modules/aws-sdk
 83M	./node_modules/googleapis

# total: 229M
```

I was wondering if you are ok to try to reduce it, but I totally understand it is a won't fix issue on your side.

## Possible Implementation
As a first goal, it seems `googleapis` is only used one time here:
https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/blob/68a27b70efcd19dcd19a9b92048ecf05358ec09f/packages/core/src/application/GCPCredentials.ts#L11

The package has been recently broken in smaller parts:
- https://github.com/googleapis/google-api-nodejs-client/issues/806#issuecomment-790920924
- https://github.com/googleapis/google-api-nodejs-client/pull/2557

If ok for you then I can have a look.

### PR DESCRIPTION
**Pull request by vhiairrassary**
## Description of Change

Reduce `core` package size by using `@google-cloud/iam-credentials` instead of `googleapis`
Fix https://github.com/cloud-carbon-footprint/cloud-carbon-footprint/issues/275 

## Checklist

- [ ] PR description included and stakeholders cc'd
- [ ] tests are changed or added
- [ ] yarn test passes
- [ ] yarn lint has been run
- [ ] git pre-commit hook is successfully executed.
      (**Please refrain from using `--no-verify`**)
- [ ] yarn changeset was run and relevant packages have been updated as a major/minor/patch bump with descriptions
      (**Determine version update using [Semantic Versioning](https://semver.org/)**)
- [ ] relevant documentation is changed or added

### CODE REVIEW

**Comment by vhiairrassary** [comment]
PR has been rebase due to conflict with upstream

**Comment by dtoakley** [comment]
Thanks for this @vhiairrassary -- changes look good! We went ahead and updated your branch again with the latest on trunk -- sorry for pushing directly to you branch! We'll do a final review and merge this down tomorrow.

**Comment by vhiairrassary** [comment]
@dtoakley Thank you a lot to consider this PR 🥳 No pb for the commits, let me know if I can do anything in the meantime

**Comment by dtoakley** [comment]
Merged! Thanks again @vhiairrassary -- this is is a solid improvement to the codebase.

**Pull request merged**
